name: AHJ-Organization of Testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project using webpack
        run: npm run build

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Deploy to GitHub Pages
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "action@github.com"
    echo "https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com" > "$HOME/.git-credentials"
    npx gh-pages -d dist -u "GitHub Actions <action@github.com>"