name: AHJ-Organization of testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: |
          npm run test
          npm run e2e:ci

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "ci@github.com"
          echo "https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com" > "$HOME/.git-credentials"
          npx gh-pages -d dist -u "github-actions[bot] <ci@github.com>"